version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jordanm88-ubuntu_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/tibor309/webtop:ubuntu@sha256:8ee7a99889a9edeadb2abe36e9e95c59be8cdfa70e30242133f2474f8e4c3e00
    security_opt:
      - seccomp:unconfined
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=yourpassword
      - CUSTOM_USER=admin
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      #- /mnt/storage:/storage:rw
    shm_size: "4gb"