version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lia_app_1
      APP_PORT: 5000
      PROXY_AUTH_ADD: "false"

  app:
    image: ghcr.io/jordanm88/lia:0.1.0
    restart: on-failure
    environment:
      ENCRYPTION_KEY: $APP_SEED
      SESSION_SECRET: $APP_SEED
      NODE_ENV: production
    volumes:
      - ${APP_DATA_DIR}/data/db:/app/data
      - ${APP_DATA_DIR}/data/uploads:/app/uploads
