version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: jordanm88-emby_server_1
      APP_PORT: 8096

  server:
    image: emby/embyserver:4.8.11.0
    environment:
      TZ: Europe/London
      UID: 1000
      GID: 1000
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config:rw
      - ${APP_DATA_DIR}/data/tvshows:/tvshows:rw
      - ${APP_DATA_DIR}/data/music:/music:rw
      - ${APP_DATA_DIR}/data/movies:/movies:rw
      - /mnt/storage:/storage:rw
