version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: jordanm88-insurancecrm_web_1
      APP_PORT: 5000
      container_name: jordanm88-insurancecrm
      # The app has its own authentication system
      # PROXY_AUTH_ADD: "false"

  app:
    image: ghcr.io/jordanm88/insurance-crm:latest
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data:rw
      - ${APP_DATA_DIR}/dist:/app/dist:rw
      - ${APP_DATA_DIR}/migrations:/app/migrations:rw
      - ${APP_DATA_DIR}/uploads:/app/uploads:rw
    environment:
      - NODE_ENV=production
      - DOMAIN=http://${DEVICE_DOMAIN_NAME}:8420
      - SESSION_SECRET=v9Zp8sTqU5dFV2LuY1nRrB6Tx3H6kAjD/Ly5QX0SjC4kB+zJfUw2HZ8Tj4PlNr1C
      - ENCRYPTION_KEY=91354942169d16a4e95695863e209cab2cce1e927a2df9e249d28b147135c2d1
